### ISSUE TITLE
Car Valet 

### ISSUE THREAD

**Issue by ISlapBuns** [Pepnsi/RedlineRP-Bugs#2]
So I’ve put my BWM M2 in the garage but anytime I try to valet it, it never gets brought to me, I’ve tried multiple tricks other players have mentioned but nothing seems to work for me, it’s insured and everything. My name on Discord is “ I Slap Buns “ and my redline character name is Dak Ell

**Comment by Pepnsi** [comment]
Will check it out.

**Comment by Pepnsi** [comment]
Seems to be a issue within the car, will see if it’s replaceable

**Comment by Pepnsi** [comment]
Being reworked
